name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ] # 如果你的主分支叫 master，请改为 master

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4 # 修正了这里：必须是 setup-node
        with:
          node-version: 20

      - name: Install and Build
        run: |
          npm install
          npm run build

      - name: Deploy
        uses: jamesives/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: gh-pages
